backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "selected_works"
    label: "Selected Works"
    folder: "content/journal"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "thumbnail", widget: "image"}
      - {label: "Snippet (Short Intro)", name: "snippet", widget: "text", required: false}
      - {label: "Location", name: "location", widget: "string", required: false}
      - label: "Project Type"
        name: "project_type"
        widget: "select"
        options: ["Pre-Wedding", "Wedding Day", "Portrait", "Commercial", "Editorial"]
        required: false
      - {label: "Member of HKPPA", name: "tag_hkppa", widget: "boolean", default: false, required: false}
      - {label: "Rosewood Approved", name: "tag_rosewood", widget: "boolean", default: false, required: false}
      - {label: "Body Text", name: "body", widget: "markdown"}

  - name: "promotion"
    label: "Promotion Settings"
    folder: "content/promotion"
    create: true
    extension: "json"
    format: "json"
    fields:
      - {label: "Show Promotion?", name: "is_active", widget: "boolean", default: false}
      - {label: "Poster Image", name: "poster", widget: "image"}
      - {label: "Expiry Date", name: "expiry_date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Email Subject", name: "subject", widget: "string", default: "Inquiry about Promotion"}
